// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow to generate Firestore security rules based on user roles and access control configurations.
 *
 * - generateSecurityRules - A function that generates Firestore security rules.
 * - GenerateSecurityRulesInput - The input type for the generateSecurityRules function.
 * - GenerateSecurityRulesOutput - The return type for the generateSecurityRules function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSecurityRulesInputSchema = z.object({
  roles: z
    .array(z.string())
    .describe('A list of user roles that need access control.'),
  certificateAccess: z
    .string()
    .describe('The access level required for certificates (e.g., read, write).'),
});
export type GenerateSecurityRulesInput = z.infer<
  typeof GenerateSecurityRulesInputSchema
>;

const GenerateSecurityRulesOutputSchema = z.object({
  securityRules: z
    .string()
    .describe('The generated Firestore security rules as a string.'),
});
export type GenerateSecurityRulesOutput = z.infer<
  typeof GenerateSecurityRulesOutputSchema
>;

export async function generateSecurityRules(
  input: GenerateSecurityRulesInput
): Promise<GenerateSecurityRulesOutput> {
  return generateSecurityRulesFlow(input);
}

const generateSecurityRulesPrompt = ai.definePrompt({
  name: 'generateSecurityRulesPrompt',
  input: {schema: GenerateSecurityRulesInputSchema},
  output: {schema: GenerateSecurityRulesOutputSchema},
  prompt: `You are an expert in generating Firestore security rules.

  Based on the provided user roles and certificate access requirements, generate Firestore security rules that ensure only users with the appropriate roles can access certificates.

  Roles: {{{roles}}}
  Certificate Access: {{{certificateAccess}}}

  Ensure that the generated rules are secure and follow Firebase best practices.

  Return the security rules as a string.
  `,
});

const generateSecurityRulesFlow = ai.defineFlow(
  {
    name: 'generateSecurityRulesFlow',
    inputSchema: GenerateSecurityRulesInputSchema,
    outputSchema: GenerateSecurityRulesOutputSchema,
  },
  async input => {
    const {output} = await generateSecurityRulesPrompt(input);
    return output!;
  }
);
